name: Teste de Carga
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      target_env:
        description: "Ambiente alvo"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production

env:
  API_BASE_PATH: "/api/v1"  # Adicionado caminho base
  K6_BIN_PATH: "/usr/bin/k6"  # Caminho explícito

jobs:
  performance-test:
    name: Teste de Carga - ${{ inputs.target_env || 'staging' }}
    runs-on: ubuntu-latest
    container:
      image: grafana/k6
      options: --user root

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Verificar estrutura do projeto
        run: |
          if [ ! -f "tests/performance/loadTest.js" ]; then
            echo "::error::Arquivo loadTest.js não encontrado!"
            exit 1
          fi
          echo "Estrutura do projeto OK"