name: Teste de Carga
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      env:
        description: "Ambiente alvo"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - production

permissions:
  contents: read
  actions: write
  checks: write

jobs:
  performance-test:
    name: Teste de Carga - ${{ inputs.env || 'staging' }}
    runs-on: ubuntu-latest
    container:
      image: grafana/k6
      options: --user root

    env:
      API_URL: ${{ inputs.env == 'production' && 'https://api.marketoflow.com' || 'https://staging.marketoflow.com' }}
      API_TOKEN: ${{ secrets.API_TOKEN }}
      K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar ambiente
        run: |
          mkdir -p /tmp/results
          chmod 777 /tmp/results

      - name: Executar teste
        run: |
          k6 run tests/performance/loadTest.js \
            --env API_URL="$API_URL" \
            --env API_TOKEN="$API_TOKEN" \
            --vus ${{ inputs.env == 'production' && '200' || '100' }} \
            --duration ${{ inputs.env == 'production' && '10m' || '5m' }} \
            ${{ env.K6_CLOUD_TOKEN && '--out cloud' || '' }} \
            --out json=/tmp/results/test_results.json \
            --summary-export=/tmp/results/summary.json

      - name: Enviar resultados
        uses: actions/upload-artifact@v4
        with:
          name: resultados-teste
          path: /tmp/results/*